"""Prompt templates package."""
from .prompts import SYSTEM_RAG_PROMPT, RAG_USER_PROMPT, STRICT_JSON_SCHEMA_INSTRUCTION
__all__ = ["SYSTEM_RAG_PROMPT", "RAG_USER_PROMPT", "STRICT_JSON_SCHEMA_INSTRUCTION"]
